export { default as Favicon } from "/public/images/favicon.png"
export { default as LogoImage } from "/public/images/logo.svg"

/* export { default as SocialYelp } from "/public/images/social-yelp.svg"
export { default as SocialGoogleStore } from "/public/images/social-google-store.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg" */

export { default as PhotoLogon } from "/public/images/logon.jpg"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as IconSearch } from "/public/images/icon-search.svg"
export { default as IconBell } from "/public/images/icon-bell.svg"
export { default as IconApplication } from "/public/images/icon-application.svg"
export { default as IconDocuments } from "/public/images/icon-documents.svg"
export { default as IconNotices } from "/public/images/icon-notices.svg"
export { default as IconPayment } from "/public/images/icon-payment.svg"
export { default as IconEdit } from "/public/images/icon-edit.svg"
export { default as IconDownload } from "/public/images/icon-download.svg"
export { default as IconPlus } from "/public/images/icon-plus.svg"
export { default as IconChevRight } from "/public/images/icon-chevron-right.svg"
export { default as IconFilter } from "/public/images/icon-filter.svg"
export { default as IconDownload2 } from "/public/images/icon-download2.svg"

export { default as SaveIcon } from "/public/images/save_icon.svg"
export { default as PlayIcon } from "/public/images/play_icon.svg"
export { default as ZelleIcon } from "/public/images/zelle_icon.svg"
export { default as CashAppIcon } from "/public/images/cash_app_icon.svg"
export { default as TickIcon } from "/public/images/tick_icon.svg"
export { default as NoteIcon } from "/public/images/icon-note.svg"
export { default as PDFIcon } from "/public/images/pdf_icon.svg"
export { default as InfoIcon } from "/public/images/info_icon.svg"
export { default as CrownIcon } from "/public/images/crown.svg"

export { default as ProfessionalWoman } from "/public/images/professional_woman.jpg"
export { default as DocumentImage } from "/public/images/document_image.svg"
export { default as NoticeImage } from "/public/images/notice_image.svg"

export { default as TransUnionImage } from "/public/images/trans_union.svg"
export { default as ExperianImage } from "/public/images/experian.svg"
export { default as EquifaxImage } from "/public/images/equifax.svg"
